import { barcode_current_initials, PAD_current_yvNo, FULL_current_numbers, DISC_current_yvNo, DRUM_current_yvNo } from "./variables";
import { createDocxDocument, writeToWord, writeToExcel} from "./EAC_helpers";


// Helper functions to generate numbers
/**
 * Generates an array of numbers within a specified range.
 *
 * @param start - The starting number of the range, inclusive.
 * @param end - The ending number of the range, inclusive.
 * @returns An array containing numbers from start to end (inclusive).
 */
function getNumberArrayInRange(start: number, end: number) {
  return Array.from({ length: end - start + 1 }, (_, i) => start + i);
}

/**
 * Converts an array of numbers into an array of strings, padding each number with zeros to ensure it is 3 digits in length.
 *
 * @param numberArray - The array of numbers to be converted.
 * @returns An array of strings, where each element is a three-digit representation of the corresponding element in the input array.
 */
function convertArrayToString(numberArray: number[], padstart: number): string[] {
  return numberArray.map((item) => item.toString().padStart(padstart, "0"));
}

// BARCODE BRAND INITIALS
const BRAND_INITIALS = Array.from(new Set(barcode_current_initials));

// PREPARE WVA Numbers and FULL DISC & DRUM Range
const PAD_WVA_RANGE: string[] = convertArrayToString(getNumberArrayInRange(10000, 37999), 0);
const DISC_DRUM_FULL_RANGE = convertArrayToString(getNumberArrayInRange(1, 1600), 3);

// Define Disc and Drum ranges in sort and remove current numbers from the full range
let DISC_RANGE: string[], DRUM_RANGE: string[];
DISC_RANGE = DRUM_RANGE = DISC_DRUM_FULL_RANGE.filter((item) => !FULL_current_numbers.includes(item));

// Define "MUST" additions for each product type
const DISC_ADDITIONS = ["", "C", "CS"];
const DRUM_ADDITIONS = [""];

// Product Type Enum
enum ProductType {
  DISC = "DISC",
  DRUM = "DRUM",
  PAD = "PAD",
  CRANKSHAFT = "CRANKSHAFT",
}

// Define "OPTIONAL" additions for each product type
const OPTIONALS = {
  [ProductType.DISC]: ["B", "H", "S"],
  [ProductType.DRUM]: ["B", "H"],
  [ProductType.PAD]: [],
  [ProductType.CRANKSHAFT]: [],
};

/**
 * Generates a list of unique EAC numbers given the initial, center, additions and product type.
 *
 * The function takes in an array of initial strings, an array of center strings, an array of addition strings, and a product type.
 * It then generates a list of EAC numbers by combining each initial with each center, and optionally adding an addition if the product type has any optional additions.
 * The generated list is then returned.
 *
 * @param initial - An array of initial strings
 * @param centers - An array of center strings
 * @param additions - An array of addition strings
 * @param product - The product type (DISC, DRUM, PAD, or CRANKSHAFT)
 * @returns A list of unique EAC numbers generated by combining the given inputs
 */
function numberGenerator(
  initial: string[],
  centers: string[],
  additions: string[],
  product: ProductType.DISC | ProductType.DRUM | ProductType.PAD | ProductType.CRANKSHAFT
): string[] {

  const codes: string[] = [];
  const optionalLength = OPTIONALS[product].length;
  let index = 0;

  initial.forEach(pre => {
    centers.forEach(center => {
      additions.forEach(add => {
        codes.push(`${pre}${center}${add}`);
      });
      if (optionalLength > 0) {
        codes.push(`${pre}${center}${OPTIONALS[product][index++ % optionalLength]}`);
      }
    });
  });

  return codes;
}

const generated: { DISC: string[]; DRUM: string[]; PAD: string[] } = 
{
  DISC: Array.from(new Set(numberGenerator(BRAND_INITIALS, DISC_RANGE, DISC_ADDITIONS, ProductType.DISC))),
  DRUM: Array.from(new Set(numberGenerator(BRAND_INITIALS, DRUM_RANGE, DRUM_ADDITIONS, ProductType.DRUM))),
  PAD: Array.from(
    new Set(PAD_WVA_RANGE.filter((item) =>
          !new Set(PAD_current_yvNo.map((each) => each.substring(0, 5))).has(item))
    )
  ),
};

const WORD_Documents = [
  { document: createDocxDocument( DISC_current_yvNo.join(","), generated.DISC.join(",")), filename: "DISC_FULL" },
  { document: createDocxDocument( DRUM_current_yvNo.join(","), generated.DRUM.join(",")), filename: "DRUM_FULL" },
  { document: createDocxDocument( PAD_current_yvNo.join(","), generated.PAD.join(",")), filename: "PAD_FULL" },
];

// Create an array of objects that contain the file name, numbers and column count to be used when writing the Excel file
const EXCEL_Sheets: { fileName: string; numbers: string[]; columnCount: number }[] = [
  { fileName: "DISC", numbers: generated.DISC.concat(DISC_current_yvNo), columnCount: 4 },
  { fileName: "DRUM", numbers: generated.DRUM.concat(DRUM_current_yvNo), columnCount: 10 },
  { fileName: "PAD", numbers: generated.PAD.concat(PAD_current_yvNo), columnCount: 10 },
];

function main() {
  writeToExcel(EXCEL_Sheets);   // Create and save the Excel file
  writeToWord(WORD_Documents);  // Create and save the Word documents
}

main();